export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_PERSON_SUCCESS = "FETCH_PERSON_SUCCESS";
export const FETCH_PERSON_FAIL = "FETCH_PERSON_FAIL";

export const EDITING_PERSON_START = "EDITING_PERSON_START";
export const EDITING_PERSON_SUCCESS = "EDITING_PERSON_SUCCESS";
export const EDITING_PERSON_FAIL = "EDITING_PERSON_FAIL";

export const SEARCH_PERSON_START = "SEARCH_PERSON_START";
export const SEARCH_PERSON_SUCCESS = "SEARCH_PERSON_SUCCESS";
export const SEARCH_PERSON_FAIL = "SEARCH_PERSON_FAIL";

export const FETCH_FAMILY = "FETCH_FAMILY";
export const FETCH_FAMILY_SUCCESS = "FETCH_FAMILY_SUCCESS";
export const FETCH_FAMILY_FAIL = "FETCH_FAMILY_FAIL";

export const ADD_RELATIVES_START = "ADD_RELATIVES_START";
export const ADD_RELATIVES_SUCCESS = "ADD_RELATIVES_SUCCESS";
export const ADD_RELATIVES_FAIL = "ADD_RELATIVES_FAIL";