export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_PERSON_SUCCESS = "FETCH_PERSON_SUCCESS";
export const FETCH_PERSON_FAIL = "FETCH_PERSON_FAIL";

export const EDITING_PERSON_START = "EDITING_PERSON_START";
export const EDITING_PERSON_SUCCESS = "EDITING_PERSON_SUCCESS";